name: build and deploy to github pages

on:
  push:
  pull_request:

jobs:
  build:
    name: build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: npm install
        run: npm i

      - name: build
        run: npm run build

      - name: deploy
        run: ./deploy.sh
        env:
          DEPLOY_USER: oatmeal
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          github_repo: ${{ github.repository }}
          github_ref: ${{ github.ref }}
          git_hash: ${{ github.sha }}
